//! ASN.1 compiler for the IEC61850 MMS part of the protocol.
//! This is used to compile the ASN.1 files into Rust modules using the
//! rasn-compiler crate.

use std::error::Error;

use rasn_compiler::prelude::*;

/// The base path for the ASN.1 files.
const BASE_PATH: &str = "src/mms/ans1";

/// The header for the generated Rust module file.
const FILE_HEADER: &str = r#"// This file was generated by the asn1-compiler tool.
// *DO NOT EDIT THIS FILE MANUALLY*.
// The asn1-compiler tool is used to compile the ASN.1 files into Rust modules
// using the rasn-compiler crate.
// The asn1-compiler tool is located in the src/mms/ans1/asn1-compiler.rs file.
// For running the asn1-compiler tool, run the following command:
// `cargo run --bin asn1-compiler`

#[rustfmt::skip]
#[allow(
	missing_docs,
	clippy::must_use_candidate,
	clippy::missing_const_for_fn,
	clippy::missing_docs_in_private_items,
	clippy::unseparated_literal_suffix
)]
"#;

fn main() -> Result<(), Box<dyn Error>> {
	// TODO: A fix was introduced in the rasn-compiler to support the any type.
	// Remove this after the next release https://github.com/librasn/compiler/commit/8219278295ab4f907b48f3dda42980032bfc9a59

	// let files = ["presentation", "acse", "mms"];
	let files = ["mms"];

	for file in &files {
		let config = RasnConfig { generate_from_impls: true, ..Default::default() };
		let result = Compiler::<RasnBackend, _>::new_with_config(config)
			.add_asn_by_path(ans1_file_path(file))
			.compile_to_string()
			.unwrap_or_else(|e| {
				panic!("Error compiling asn1 file {}: \n{e}", ans1_file_path(file))
			});
		#[allow(clippy::print_stdout)]
		for warning in result.warnings {
			println!("warning: {:?}", warning);
		}
		let rs_file_path = rs_file_path(file);
		let generated_code = format!("{FILE_HEADER}{}", result.generated);
		std::fs::write(rs_file_path.clone(), generated_code)
			.unwrap_or_else(|_| panic!("Error writing Rust module file {rs_file_path}"));
	}

	Ok(())
}

/// Returns the path to the ASN.1 file for the given file name.
fn ans1_file_path(file: &str) -> String {
	format!("{BASE_PATH}/{}.asn", file)
}

/// Returns the path to the Rust module file for the given file name.
fn rs_file_path(file: &str) -> String {
	format!("{BASE_PATH}/{}.rs", file)
}
